version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    parameters:
      servicename:
        type: string
    steps:
      - checkout
      - run: cd src/<< parameters.servicename >>
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  log_processing:
    jobs:
      - test:
          servicename: log-processing